# Generated by Django 5.1.5 on 2025-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_manager', '0003_csvchanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedcsv',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed_processing', 'Failed Processing')], default='unprocessed', max_length=20),
        ),
    ]
